spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: aimeng
  application:
    name: user-center
server:
  port: 901
eureka:
  client:
    serviceUrl:
      #服务注册地址
      defaultZone: http://127.0.0.1:801/eureka/
